---
- name: config public key
  hosts: all
  tasks:
    - name: upload root pubkey
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
