---
- name: config webservers
  hosts: webservers
  tasks:
    - name: insall web pkgs
      yum:
        name: [httpd, php, php-mysql]
        state: latest
    - name: start web services
      service:
        name: httpd
        state: started
        enabled: yes

- name: config dbservers
  hosts: dbservers
  tasks:
    - name: install db pkgs
      yum:
        name: mariadb-server
        state: latest
    - name: start db services
      service:
        name: mariadb
        state: started
        enabled: yes
