---
- name: configure dbservers
  hosts: dbservers
  tasks:
  - name: install db pkgs
    yum:
      name: mariadb-server
      state: latest
  - name: start db srv
    service:
      name: mariadb
      state: started
      enabled: yes

- name: configure webservers
  hosts: webservers
  tasks:
  - name: install web pkgs
    yum:
      name: [httpd, php, php-mysql]
      state: latest
  - name: start web srv
    service:
      name: httpd
      state: started
      enabled: yes
