---
- name: configure db servers
  hosts: dbservers
  tasks:
    - name: install db pkgs
      yum:
        name: mariadb-server
        state: latest
    - name: start db service
      service:
        name: mariadb
        state: started
        enabled: yes

- name: configure web servers
  hosts: webservers
  tasks:
    - name: install web pkgs
      yum:
        name: [httpd, php, php-mysql]
        state: present
    - name: start web service
      service:
        name: httpd
        state: started
        enabled: yes
